version: '3.3'

services:
  demo-tensorflow-js:
    build: /.
    ports:
      - "4200:4200"
  proxy-server:
    build: nginx/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certs:/tmp/ssl

